"""
Rewrite placeholder menu-item descriptions with a LOCAL Ollama model.

The generator (generate_data.py) leaves each item's description as a placeholder
("<item> at <truck>"). This script replaces each with a short, appetizing,
context-aware description generated by your local Ollama server.

WHY A SEPARATE LOCAL SCRIPT:
  Ollama runs on YOUR machine at http://localhost:11434. Run this locally.

USAGE (from the foodtruck-cuisine/ folder):
  python enrich_descriptions.py                 # auto-detect a model, enrich placeholders only
  python enrich_descriptions.py --model llama3.2 # pick a specific model
  python enrich_descriptions.py --force          # rewrite ALL descriptions, not just placeholders
  python enrich_descriptions.py --limit 20       # only do the first 20 (quick test)
  python enrich_descriptions.py --dry-run        # build prompts, don't call Ollama or write

Safe to re-run: it backs up once to menu_items.backup.json, saves progress every
25 items, and by default skips items already enriched (so you can resume).

Stdlib only — no pip install needed.
"""

import argparse, json, os, sys, time, urllib.request, urllib.error

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
OLLAMA = os.environ.get("OLLAMA_HOST", "http://localhost:11434")

SYSTEM = (
    "You are a food-truck menu copywriter. Write ONE punchy menu description, "
    "grounded in the item's REAL ingredients.\n"
    "Rules:\n"
    "- 8 to 16 words. A single sentence or fragment.\n"
    "- Present tense. No quotation marks, no markdown, no emojis.\n"
    "- Do NOT restate the item name and do NOT mention the price.\n"
    "- Mention 1-2 of the listed ingredients or a texture; never invent ingredients.\n"
    "- Respect the diet: never imply meat or fish for vegetarian/vegan items; "
    "never imply dairy or egg for vegan or dairy-free items.\n"
    "- Match the vibe to the truck's price tier.\n"
    "- Banned words: delicious, mouth-watering, scrumptious, yummy, tasty, flavorful.\n"
    "Return ONLY the description."
)

# few-shot examples steer small models toward the target length/voice
FEWSHOT = (
    "Example 1\n"
    "Item: Al Pastor Taco | casual street-food energy | ingredients: corn tortilla, pork, pineapple\n"
    "-> Marinated pork and charred pineapple piled on a warm double corn tortilla.\n\n"
    "Example 2\n"
    "Item: Ahi Tuna Poke Bowl | elevated and refined | ingredients: rice, tuna, edamame, seaweed\n"
    "-> Sushi-grade tuna over seasoned rice with edamame and a whisper of nori.\n\n"
    "Example 3 (vegan — no dairy, no meat words)\n"
    "Item: Tofu Veggie Bowl | approachable and fresh | ingredients: rice, tofu, edamame, cucumber\n"
    "-> Crisp cucumber, cool edamame and marinated tofu piled over fluffy rice.\n\n"
)

# trivial items get fixed copy — no point asking an LLM to wax poetic about water
TRIVIAL = {
    "Bottled Water": "Chilled bottled spring water.",
    "Soft Drink": "Ice-cold soda, your choice of flavor.",
}

TIER_TONE = {
    "$": "casual street-food energy",
    "$$": "approachable and fresh",
    "$$$": "elevated and refined",
    "$$$$": "premium, chef-driven",
    None: "friendly and fresh",
}


def http_json(url, payload=None, timeout=120):
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data,
                                 headers={"Content-Type": "application/json"},
                                 method="POST" if data else "GET")
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode())


def list_models():
    try:
        tags = http_json(f"{OLLAMA}/api/tags", timeout=10)
        return [m["name"] for m in tags.get("models", [])]
    except Exception:
        return []


def pick_model(requested):
    available = list_models()
    if requested:
        # accept "llama3.2" matching "llama3.2:latest"
        for m in available:
            if m == requested or m.split(":")[0] == requested:
                return m
        print(f"! Requested model '{requested}' not found. Available: {available or 'none'}")
        sys.exit(1)
    if not available:
        print("! No Ollama models found. Is Ollama running? Try:  ollama pull llama3.2")
        sys.exit(1)
    # prefer a small instruct model if present, else first
    for pref in ("llama3.2", "llama3.1", "llama3", "qwen2.5", "mistral", "phi3", "gemma2"):
        for m in available:
            if m.split(":")[0] == pref:
                return m
    return available[0]


def build_prompt(item, truck, ingredients):
    cuisines = ", ".join(truck.get("cuisines") or []) or "street food"
    diet = ", ".join(item.get("dietary_tags") or []) or "no special diet"
    spice = item.get("spice_level", "none")
    tone = TIER_TONE.get(truck.get("price_tier"), TIER_TONE[None])
    ings = ", ".join(ingredients) if ingredients else "chef's choice"
    return (
        FEWSHOT +
        "Now write the description for this item:\n"
        f"Item: {item['name']}\n"
        f"Category: {item['category']}\n"
        f"Food truck: {truck['name']} (cuisine: {cuisines})\n"
        f"Price tier tone: {tone}\n"
        f"Dietary: {diet}\n"
        f"Spice level: {spice}\n"
        f"Real ingredients: {ings}\n"
        "-> "
    )


def generate(model, prompt):
    resp = http_json(f"{OLLAMA}/api/generate", {
        "model": model,
        "system": SYSTEM,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.8, "num_predict": 60},
    })
    text = (resp.get("response") or "").strip()
    # tidy: drop echoed arrow / surrounding quotes / stray prefixes
    if text.startswith("->"):
        text = text[2:].strip()
    text = text.strip().strip('"').strip("'").strip()
    if text.lower().startswith("description:"):
        text = text.split(":", 1)[1].strip()
    return " ".join(text.split())


def is_placeholder(item, truck):
    return item.get("description", "") == f"{item['name']} at {truck['name']}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=None)
    ap.add_argument("--force", action="store_true", help="rewrite all, not just placeholders")
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    items = json.load(open(os.path.join(DATA, "menu_items.json")))
    trucks = {t["id"]: t for t in json.load(open(os.path.join(DATA, "trucks.json")))}
    # real ingredients per item (grounds the copy, prevents hallucination)
    ing_names = {i["id"]: i["name"] for i in json.load(open(os.path.join(DATA, "ingredients.json")))}
    item_ings = {}
    for rl in json.load(open(os.path.join(DATA, "recipes.json"))):
        item_ings.setdefault(rl["menu_item_id"], []).append(ing_names.get(rl["ingredient_id"], ""))

    model = None
    if not args.dry_run:
        model = pick_model(args.model)
        print(f"Using Ollama model: {model}  ({OLLAMA})")

    # backup once
    backup = os.path.join(DATA, "menu_items.backup.json")
    if not os.path.exists(backup) and not args.dry_run:
        json.dump(items, open(backup, "w"), indent=2)
        print(f"Backed up original -> {os.path.basename(backup)}")

    targets = []
    for it in items:
        tr = trucks.get(it["truck_id"])
        if not tr:
            continue
        if args.force or is_placeholder(it, tr):
            targets.append((it, tr))
    if args.limit:
        targets = targets[:args.limit]

    print(f"{len(targets)} items to enrich"
          + (" (dry run — no calls, no writes)" if args.dry_run else "") + "\n")

    if args.dry_run:
        for it, tr in targets[:3]:
            print("--- PROMPT PREVIEW ---")
            print(build_prompt(it, tr, item_ings.get(it["id"], [])))
            print()
        print(f"(showed 3 of {len(targets)} prompts)")
        return

    t0 = time.time()
    done = 0
    for i, (it, tr) in enumerate(targets, 1):
        if it["name"] in TRIVIAL:            # fixed copy, skip the model
            it["description"] = TRIVIAL[it["name"]]
            done += 1
            continue
        try:
            desc = generate(model, build_prompt(it, tr, item_ings.get(it["id"], [])))
            if desc:
                it["description"] = desc
                done += 1
        except (urllib.error.URLError, TimeoutError) as e:
            print(f"  ! error on {it['id']} ({it['name']}): {e} — skipping")
            continue
        if i % 10 == 0 or i == len(targets):
            rate = i / max(time.time() - t0, 1e-6)
            eta = (len(targets) - i) / max(rate, 1e-6)
            print(f"  {i}/{len(targets)}  ({done} written)  ~{rate:.1f}/s  ETA {eta/60:.1f} min")
        if i % 25 == 0:  # checkpoint
            json.dump(items, open(os.path.join(DATA, "menu_items.json"), "w"), indent=2)

    json.dump(items, open(os.path.join(DATA, "menu_items.json"), "w"), indent=2)
    print(f"\nDone. Rewrote {done} descriptions in {(time.time()-t0)/60:.1f} min.")
    print("Sample:")
    for it, tr in targets[:3]:
        print(f"  • {it['name']} ({tr['name']}): {it['description']}")


if __name__ == "__main__":
    main()
